### ISSUE TITLE
Sample to iterate a list to create dynamic LI elements.

### ISSUE THREAD

**Issue by jsoques** [basxsoftwareassociation/htmlgenerator#13]
Hello, I'm fairly new to Python.  Would you have a sample to create LI elements from a list? I tried this `hg.UL(hg.LI([item for item in menu]), _class="menu")` but does not work and I cannot grasp how to do it. Thanks.

**Comment by saemideluxe** [comment]
Sure. The issue here is, that the HTML element expects each child element as a single parameter, for example:

    hg.UL(hg.LI("1"), hg.LI("2"), HG.LI("3"))

In your example, you are passing a list as a single parameter, which the renderer then assumes to be a single element. In order to get the desired result, you need to "unpack" the list. In Python you can unpack a normal list into multiple parameters by using the unpack operator `*`.

In your case, you would likely want something like

    hg.UL(*[hg.LI(item) for item in menu], _class="menu")

If we assume your menu-list has the items `[item1, item2, item3]` then Python would internally treat this like

    hg.UL(hg.LI(item1), hg.LI(item1), hg.LI(item1), _class="menu")
 
You never see this, the interpreter does this "unpacking" into multiple parameters automatically.
Also, notice that the `hg.LI` element needs to be part of the list comprehension, in order to generate multiple elements.

**Comment by jsoques** [comment]
Thanks. I'll try that ASAP.

**Comment by jsoques** [comment]
Thanks, that worked.
